# Site settings
title: Siria Serrano
email: serrano.siria@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Siria Serrano is an Afro-Latina poet, writer, and social justice activist.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://siriaserrano.com" # the base hostname & protocol for your site
twitter_username: #
github_username:  #

# Build settings
markdown: kramdown

#port: 8080
